### ISSUE TITLE
Mimic np [:,:] behavior

### ISSUE THREAD

**Issue by atotalnoob** [SciSharp/NumSharp#243] opened 2019-04-09 00:26 UTC
Hi, 

How would I mimic np [:,X] or [X,:] behavior in numSharp?

**Comment by henon** [comment] 2019-04-09 00:29
duplicate of https://github.com/SciSharp/NumSharp/issues/238 please check it out

as of now it is not entirely implemented

**Comment by Oceania2018** [comment] 2019-04-09 00:32
We'll wait for .net standard 2.1, it introduces new syntax to index: https://github.com/dotnet/csharplang/issues/2148

**Comment by Esther2013** [comment] 2019-04-09 02:02
Currently we use `string` as indexing, it works so far.

**Comment by henon** [comment] 2019-04-12 11:39
please discuss further at #238

**Closed by henon** 2019-04-12 11:39 UTC
