### ISSUE TITLE
NDArray.transpose()

### ISSUE THREAD

**Issue by pkingwsd** [SciSharp/NumSharp#222] opened 2019-03-21 03:44 UTC
like this:

        img4 = np.array(img3)[:,:,::-1]
        img5 = img3.transpose(0,3,1,2)

**Comment by henon** [comment] 2019-06-15 18:12
duplicate of [117](https://github.com/SciSharp/NumSharp/issues/117)

**Closed by henon** 2019-06-15 18:12 UTC
Labels: help wanted

**Comment by Nucs** [comment] 2019-09-29 11:58
`np.swapaxes`, `np.transpose`, `np.moveaxis` and `np.rollaxis` were added in the [this commit](https://github.com/SciSharp/NumSharp/commit/39896599ac40584821802cfd63a15458060289ba ).
And will be released soon in 0.20.4.
