### ISSUE TITLE
np.maximum, np.minimum

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#359] opened 2019-10-05 23:41 UTC
`np.maximum` Element-wise maximum of array elements.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html

`np.minimum` Element-wise minimum of array elements.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html

**Comment by Nucs** [comment] 2019-10-11 07:55
Added in https://github.com/SciSharp/NumSharp/commit/af8221b6e68a7f8bdbf503302f3fac69d930d141 .

**Comment by Oceania2018** [comment] 2019-10-11 23:49
![image](https://user-images.githubusercontent.com/1705364/66690662-18915b80-ec57-11e9-9bf5-7f723af2fd70.png)

Exception due to `Slice` is null:

![image](https://user-images.githubusercontent.com/1705364/66690748-c0a72480-ec57-11e9-8f13-01d1501bad9a.png)

**Comment by Nucs** [comment] 2019-10-12 00:32
This code tells me nothing, I need a reproducing unit test.

**Comment by Oceania2018** [comment] 2019-10-12 01:23
@Nucs Added Unit Test https://github.com/SciSharp/NumSharp/commit/5212e8203161a5095960a0fcdbfb9abf9b175210

**Comment by Nucs** [comment] 2019-10-12 08:37
@henon The issue is within Shape.GetCoordinates, can you take a look please.

**Comment by henon** [comment] 2019-10-12 10:50
fixed

**Comment by Oceania2018** [comment] 2019-10-12 12:27
@henon @Nucs I've updated the unit test. still has problem.

**Comment by henon** [comment] 2019-10-12 13:14
yes, you are right, my bad.

**Comment by Nucs** [comment] 2019-10-12 13:55
Fixed in https://github.com/SciSharp/NumSharp/commit/c54ce96ffe3b83f804afb3297181a89bc37431ba

**Comment by Oceania2018** [comment] 2019-10-12 14:14
Confirmed:
![image](https://user-images.githubusercontent.com/1705364/66702738-888ff800-ecd0-11e9-8640-9299f023a62a.png)

Compared to NumSharp:
![image](https://user-images.githubusercontent.com/1705364/66702702-1c14f900-ecd0-11e9-956c-2067e7b840b5.png)


Perfect, @henon @Nucs

**Comment by Oceania2018** [comment] 2019-10-12 14:26
np.minimum is not correct:

![image](https://user-images.githubusercontent.com/1705364/66702919-5ed7d080-ecd2-11e9-8a15-c642a023d1fd.png)


![image](https://user-images.githubusercontent.com/1705364/66702908-4071d500-ecd2-11e9-9459-ba1443eb51d5.png)

**Comment by Nucs** [comment] 2019-10-12 14:37
@Oceania2018 Please add a **new** reproducing test unit.
You don't have to push to master, pasting it here is fine.

**Comment by Oceania2018** [comment] 2019-10-12 14:40
Pushed unit test.

**Comment by Nucs** [comment] 2019-10-12 14:46
Don't change an existing unit test that is related to a fix we pushed. I'll push the old unit test.

**Comment by henon** [comment] 2019-10-12 18:23
and fixed

**Comment by Oceania2018** [comment] 2019-10-12 19:37
Doesn't work in ndarray[nd]?

![image](https://user-images.githubusercontent.com/1705364/66706800-4335ef80-ecfd-11e9-9a4d-4631255241d8.png)

```shell
System.NotSupportedException: Specified method is not supported.
   at NumSharp.NDArray.set_Item(Object[] indices_or_slices, NDArray value) in D:\SciSharp\NumSharp\src\NumSharp.Core\Selection\NDArray.Indexing.cs:line 202
```

**Comment by henon** [comment] 2019-10-12 19:50
min max works now

**Closed by henon** 2019-10-12 19:50 UTC
Labels: enhancement
