### ISSUE TITLE
nd[np.newaxis, :]

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/NumSharp#355] opened 2019-10-04 03:28 UTC
Can we support `nd[np.newaxis, :]` and `nd[:, np.newaxis]` ?

![image](https://user-images.githubusercontent.com/1705364/66179033-fd0dcb80-e62c-11e9-8b0f-4acd7d5f8426.png)

**Comment by Nucs** [comment] 2019-10-04 06:27
Duplicate of https://github.com/SciSharp/NumSharp/issues/344.

**Closed by Nucs** 2019-10-04 06:27 UTC
Labels: enhancement

**Comment by Nucs** [comment] 2019-10-04 06:37
Untill then:
`nd[np.newaxis, :] == np.expand_dim(nd, 0)`
`nd[:, np.newaxis] == np.expand_dim(nd, -1)`

**Comment by Oceania2018** [comment] 2019-10-04 11:13
Cool

**Comment by henon** [comment] 2019-10-04 17:53
I just implemented it in PR https://github.com/SciSharp/NumSharp/pull/357
